#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-only

#Symlinks

PLAT=$(/opt/zimbra/libexec/get_plat_tag.sh)
if [[ $PLAT == "UBUNTU"* || $PLAT == "DEBIAN"* ]]; then
  if [ ! -e "/usr/sbin/sendmail" -o -L "/usr/bin/sendmail" ]; then
     if [ -L "/usr/bin/sendmail" ]; then
       if [ -x /bin/readlink ]; then
         SMPATH=$(/bin/readlink /usr/sbin/sendmail)
         if [ x$SMPATH = x"/opt/zimbra/postfix/sbin/sendmail" -o x$SMPATH = x"/opt/zimbra/common/sbin/sendmail" ]; then
            /bin/rm -f /usr/sbin/sendmail
            ln -s /opt/zimbra/common/sbin/sendmail /usr/sbin/sendmail
          fi
       fi
     else
       ln -s /opt/zimbra/common/sbin/sendmail /usr/sbin/sendmail
     fi
  fi
fi

egrep -q '^%zimbra[[:space:]]' /etc/sudoers
if [ $? = 0 ]; then
  sudotmp=`mktemp -t zsudoers.XXXXXX 2> /dev/null` || { echo "Failed to create tmpfile"; exit 1; }
  SUDOMODE=`perl -e 'my $mode=(stat("/etc/sudoers"))[2];printf("%04o\n",$mode & 07777);'`
  egrep -v '^%zimbra[[:space:]]' /etc/sudoers > $sudotmp
  mv -f $sudotmp /etc/sudoers
  chmod $SUDOMODE /etc/sudoers
fi
chmod 440 /etc/sudoers.d/02_zimbra-mta
chown root:root /etc/sudoers.d/02_zimbra-mta

chown zimbra:zimbra /opt/zimbra/common/conf/master.cf.in
chmod 440 /opt/zimbra/common/conf/master.cf.in
chown zimbra:zimbra /opt/zimbra/common/conf/tag_as_*.re.in

mkdir -p /opt/zimbra/data/amavisd/db
mkdir -p /opt/zimbra/data/amavisd/tmp
mkdir -p /opt/zimbra/data/amavisd/var
mkdir -p /opt/zimbra/data/amavisd/quarantine
chown -R zimbra:zimbra /opt/zimbra/data/amavisd/*

mkdir -p /opt/zimbra/data/opendkim
chown -R zimbra:zimbra /opt/zimbra/data/opendkim

mkdir -p /opt/zimbra/data/clamav/db
chown -R zimbra:zimbra /opt/zimbra/data/clamav/db

mkdir -p /opt/zimbra/data/postfix/spool/pid
chown postfix:zimbra /opt/zimbra/data/postfix
chown root:postfix /opt/zimbra/data/postfix/spool
chown postfix:root /opt/zimbra/data/postfix/spool/pid

chown zimbra:zimbra /opt/zimbra/data

if [ ! -f /opt/zimbra/common/conf/main.cf ]; then
	touch /opt/zimbra/common/conf/main.cf
	chown zimbra:zimbra /opt/zimbra/common/conf/main.cf
fi

if [ ! -e /etc/aliases -o -L /etc/aliases ]; then
  if [ -L /etc/aliases ]; then
    if [ -x /bin/readlink ]; then
      SMPATH=$(/bin/readlink /etc/aliases)
      if [ x$SMPATH = x"/opt/zimbra/postfix/conf/aliases" -o x$SMPATH = x"/opt/zimbra/common/conf/aliases" ]; then
        rm -f /etc/aliases
        ln -s /opt/zimbra/common/conf/aliases /etc/aliases
      fi
    fi
  else
    ln -s /opt/zimbra/common/conf/aliases /etc/aliases
  fi
fi

if [ -x "/opt/zimbra/libexec/zmfixperms" ]; then
  /opt/zimbra/libexec/zmfixperms
fi

chgrp zimbra /opt/zimbra/common/conf
chmod g+w /opt/zimbra/common/conf
